@startuml
    component [fluentapi] #Green
    component [assertion]
    component [extraction]
    component [projection]
    component [uml]
    component [calculation]
    component [util]
    [fluentapi] -> [assertion]
    [fluentapi] -> [uml]
    [fluentapi] -> [extraction]
    [fluentapi] -> [projection]
    [fluentapi] -> [calculation]
    [assertion] -> [projection]
    [projection] -> [projection/cycles]
    [projection] -> [extraction]
    [projection] -> [calculation]
    [extraction] -> [util]
    [extraction] -> [error]
    [uml] -> [assertion]
    [calculation] -> [extraction]
    [util] -> [fluentapi]
@enduml
