name: Integrate
on:
    - push
    - pull_request
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x
            - name: Cache node modules
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
                  restore-keys: |
                      npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
                      npm-${{ runner.os }}-
            - uses: actions/checkout@v3
            - run: npm ci
            - run: npm run lint
            - run: npm run test
